engines:
  pep8:
    enabled: true

  markdownlint:
    enabled: true

  sonar-python:
    enabled: true

plugins:
  bandit:
    enabled: true
    config:
      python_version: 3

exclude_patterns:
  - "**/.venv/"
  - "**/.data/"
  - "**/.pytest_cache/"
  - "**/.vscode/"
  - "**/.tox/"
  - "**/.dist/"
