engines:
  pep8:
    enabled: true

  markdownlint:
    enabled: true

  sonar-python:
    enabled: true

exclude_patterns:
  - "**/.venv/"
  - "**/.data/"
  - "**/.pytest_cache/"
  - "**/.vscode/"
  - "**/tests/"
  - "**/.tox/"
  - "**/.dist/"
