repos:
  - repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/PyCQA/bandit
    rev: 1.5.1
    hooks:
      - id: bandit
        language: python
