version: "3.5"
services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    volumes:
      - .:/api
    command: ["flask", "run", "--host=0.0.0.0", "--port=${PORT}"]

  web_test:
    build: .
    env_file: .env
    command: ["tox"]
